variables:
 net_name: "gitlab-autoscale"
 instance_type: "m1.small"
 key_name: "bh9_testing"
 sec_grps: 'cloudforms_ssh_in,internal_etcd,netdata,cockroachdb'
 auth_url: "http://delta.internal.sanger.ac.uk:5000/v2.0/"

stages:
 - imagecreate
 - deploy

xenial_image_creation:
  stage: imagecreate
  tags:
   - openstack-autoscale
   - packer-autoscale
  script:
   - export OS_AUTH_URL=$auth_url
   - imagelist=$(openstack image list | grep 'Xenial etcd')
   - if [ -z imagelist ]; then
   - /software/packer-0.9.0/bin/packer build xenial_template.json
   - fi

centos_image_creation:
  stage: imagecreate
  tags:
   - openstack-autoscale
   - packer-autoscale
  script:
   - export OS_AUTH_URL=$auth_url
   - imagelist=$(openstack image list | grep 'Centos etcd')
   - if [ -z imagelist ]; then
   - /software/packer-0.9.0/bin/packer build centos_template.json
   - fi

openstack_stack_create:
  stage: deploy
  tags:
   - openstack-autoscale
  script:
   - sec_grps=$(echo $sec_grps | cut -d\' -f2)
   - export OS_AUTH_URL=$auth_url
   - echo $sec_grps
   - openstack stack create --wait -t template.yaml --parameter OS_AUTH_URL="$auth_url" --parameter OS_USERNAME="$OS_USERNAME" --parameter OS_TENANT_NAME="$OS_TENANT_NAME" --parameter OS_PASSWORD="$OS_PASSWORD" --parameter net_name="$net_name" --parameter image="Xenial etcd" --parameter sec_grps="$sec_grps" --parameter instance_type="$instance_type" --parameter key_name="$key_name" --parameter configscript="cockroach.sh" a$CI_BUILD_ID
   - sleep 300
   - ./test.sh
#   - openstack stack delete --yes a$CI_BUILD_ID

centos_stack_create:
  stage: deploy
  tags:
   - openstack-autoscale
  script:
   - sec_grps=$(echo $sec_grps | cut -d\' -f2)
   - export OS_AUTH_URL=$auth_url
   - echo $sec_grps
   - openstack stack create --wait -t template.yaml --parameter OS_AUTH_URL="$auth_url" --parameter OS_USERNAME="$OS_USERNAME" --parameter OS_TENANT_NAME="$OS_TENANT_NAME" --parameter OS_PASSWORD="$OS_PASSWORD" --parameter net_name="$net_name" --parameter image="Centos etcd" --parameter sec_grps="$sec_grps" --parameter instance_type="$instance_type" --parameter key_name="$key_name" --parameter configscript="cockroach.sh" a$CI_BUILD_ID
   - sleep 300
   - ./test.sh
#   - openstack stack delete --yes a$CI_BUILD_ID

openstack_stack_create:
  stage: deploy
  tags:
   - openstack-autoscale
  script:
   - sec_grps=$(echo $sec_grps | cut -d\' -f2)
   - export OS_AUTH_URL=$auth_url
   - echo $sec_grps
   - openstack stack create --wait -t template.yaml --parameter OS_AUTH_URL="$auth_url" --parameter OS_USERNAME="$OS_USERNAME" --parameter OS_TENANT_NAME="$OS_TENANT_NAME" --parameter OS_PASSWORD="$OS_PASSWORD" --parameter net_name="$net_name" --parameter image="Trusty etcd" --parameter sec_grps="$sec_grps" --parameter instance_type="$instance_type" --parameter key_name="$key_name" --parameter configscript="cockroach.sh" a$CI_BUILD_ID
   - sleep 300
   - ./test.sh
#   - openstack stack delete --yes a$CI_BUILD_ID
 
