variables:
 net_name: "CI_net"
 image: "Ubuntu Xenial"
 instance_type: "m1.small"
 key_name: "bh9_testing"
 sec_grps: '["cloudforms_ssh_in","internal_etcd","netdata","my_service_sec_grp"]'

stages:
 - deploy

openstack_stack_create:
  stage: deploy
  tags:
   - openstack-autoscale
  script:
   - openstack stack create -t template.yaml --parameter OS_USERNAME=$OS_USERNAME  --parameter OS_TENANT_NAME=$OS_TENANT_NAME --parameter OS_PASSWORD=$OS_PASSWORD --parameter net_name=$net_name --parameter image=$image --parameter sec_grps=$sec_grps --parameter instance_type=$instance_type --parameter key_name=$key_name --parameter configscript="cockroach.sh" test$CI_BUILD_ID

