heat_template_version: 2015-10-15

parameters:
  key_name:
    type: string
    label: Key Name
    description: Name of key-pair to be used for compute instance
  image:
    type: string
    label: Image Name
    description: Image to be used for compute instance
    default: Ubuntu Xenial #Note: Currently only works on Xenial and Centos
  instance_type:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
    default: m1.tiny
  net_name:
    type: string
    label: Network Name
    description: Name of the network to use
  sec_grps:
    type: comma_delimited_list
    label: a comma separated list of security groups
    description: The list of security groups your instances require
    default: ["cockroachdb","internal_etcd","cloudforms_ssh_in","netdata"]
  etcdclientport:
    type: number
    label: etcd client-side port
    description: the tcp port over which etcd serves client requests
    default: 12379
  OS_USERNAME:
    type: string
    label: Your username
    hidden: true
  OS_PASSWORD:
    type: string
    label: Your password
    hidden: true
  OS_TENANT_NAME:
    type: string
    label: Your tenant name
    hidden: true
  OS_REGION:
    type: string
    label: Your region
    default: "regionOne"
  OS_AUTH_URL:
    type: string
    label: The authorisation url for openstack
    default: "http://delta.internal.sanger.ac.uk/5000/v2.0/"
  etcdpeerport:
    type: number
    label: etcd peer-side port
    description: the tcp port over which etcd communicates with the rest of the cluster
    default: 12380
  retries:
    type: number
    label: the number of attempt that should be made to join the etcd cluster
    default: 10
  metrics_server:  
    type: string
    label: the ip address of the metrics server (if there is one)
  superstack:
    type: string
    label: the top level stack id
  pool_id:
    type: string
    label: the pool_id, do not use as it will be overwritten by the main template
  protocol_port:
    type: number
    label: the port used by you application
  subnet:
    type: string
    label: the subnet name for the load balancer

resources:
  proxy:
    type: OS::Nova::Server
    properties:
      name: etcd-proxy
      key_name:
        get_param: key_name  #use a pre-registered key for access after creation
      image:
        get_param: image     #which image to use for the VM
      config_drive: true
      flavor:
        get_param: instance_type       #which flavor of instance to boot
      networks:
        - "network":
            get_param: net_name    #which private network to put the instance on
      security_groups:
        get_param: sec_grps
#     metadata: {"metering.stack": {get_param: "OS::stack_name"}}
      personality:
        /home/etcd/etcd2.service:
          get_file: etcd/etcd_etcd2.service
      #/home/ubuntu/locking.py:
       # str_replace:
        #  template:
         #   get_file: etcd/etcd_locking.py
          #params:
           # $thisisatimeout:
            #  get_param: scaledownperiod
        #    $thisisaclientport:
         #     get_param: etcdclientport
          #  $thisisanattemptperiod:
           #   get_param: lockattemptperiod
     # /home/ubuntu/suicide.service:
      #  get_file: etcd/etcd_suicide.service
      #/home/ubuntu/etcd2.service:
       # get_file: etcd/etcd_etcd2.service
        /home/etcd/configscript.sh:
          str_replace:
            template:
              get_file: proxyconfig.sh
            params:
              $thisisaclientport:
                get_param: etcdclientport
#      /home/ubuntu/cleanup.sh:
 #         get_file: cleanupscript.sh

      user_data_format: RAW
      user_data:
        str_replace:
          template:
            get_file: etcd/etcd_proxy_autoscale.sh
          params:
            $thisisausername:
              get_param: OS_USERNAME
            $thisisapassword:
              get_param: OS_PASSWORD
            $thisisatenantname:
              get_param: OS_TENANT_NAME
            $thisisaregion:
              get_param: OS_REGION
            #$thisisatimeout: {get_param: scaledownperiod}
            $thisisametricserver:
              get_param: metrics_server
            #$thisisascriptname: {get_param: configscript}
            $thisisaurl:
              get_param: OS_AUTH_URL
            $thisisapeerport:
              get_param: etcdpeerport
            $thisisaclientport:
              get_param: etcdclientport
            $thisisaretrycount:
              get_param: retries
            $thisisastackname:
              get_param: superstack
  member:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      pool:
        get_param: pool_id
      address:
        get_attr: [proxy, first_address]
      protocol_port:
        get_param: protocol_port
      subnet:
        get_param: subnet

